### ISSUE TITLE
TACX Bushido 1980

### ISSUE THREAD

**Issue by gibabuscape** [WouterJD/FortiusANT#431] opened 2023-05-03 15:38 UTC
I have a Bushido T1980 and I would like to know if there is anyone who has already installed FortiusAnt with Bkool? Are there any specific instructions for the T1980? @WouterJD

**Comment by WouterJD** [comment] 2023-05-03 16:46
Hi @gibabuscape 

I assume you have read the manual and managed to get FortiusAnt linked to your bushido; **please confirm that this is correct.**
From that moment onwards, your bushido is not communicating with Bkool, but FortiusAnt does.

Please provide some more details
- what set-up do you use
- what happens after starting FortiusAnt - how far do you get
- does any other CTP work in your environment?

**Comment by gibabuscape** [comment] 2023-05-03 18:33
> Please, see below the erro when  started FortiusAnt

![image](https://user-images.githubusercontent.com/132455145/236010853-25570111-355e-40b1-807d-69f94e84449d.png)

**Comment by gibabuscape** [comment] 2023-05-03 18:34
> > Please, see below the erro when  started FortiusAnt
> 
> ![image](https://user-images.githubusercontent.com/132455145/236010853-25570111-355e-40b1-807d-69f94e84449d.png)

[FortiusAntSettingjson.txt](https://github.com/WouterJD/FortiusANT/files/11389794/FortiusAntSettingjson.txt)

**Comment by WouterJD** [comment] 2023-05-05 13:07
Hi @gibabuscape the problem is caused by an imort from bless and is resolved in the current version; please update.
See https://github.com/WouterJD/FortiusANT/blob/master/pythoncode/FortiusAnt.py#L644

**Comment by gibabuscape** [comment] 2023-05-05 14:03
WouterJD, tks a lot for you support.

I don't know Python, is it possible to have the executable?


De: Wouter Dubbeldam ***@***.***>
Enviada em: sexta-feira, 5 de maio de 2023 10:08
Para: WouterJD/FortiusANT ***@***.***>
Cc: Gilberto Faria ***@***.***>; Mention ***@***.***>
Assunto: Re: [WouterJD/FortiusANT] TACX Bushido 1980 (Issue #431)


Hi @gibabuscape<https://github.com/gibabuscape> the problem is caused by an imort from bless and is resolved in the current version; please update.
See https://github.com/WouterJD/FortiusANT/blob/master/pythoncode/FortiusAnt.py#L644

**Comment by WouterJD** [comment] 2023-05-05 14:05
> is it possible to have the executable?

Yes, I just uploaded it

**Comment by gibabuscape** [comment] 2023-05-05 18:44
Tks man!!!

De: Wouter Dubbeldam ***@***.***>
Enviada em: sexta-feira, 5 de maio de 2023 11:06
Para: WouterJD/FortiusANT ***@***.***>
Cc: Gilberto Faria ***@***.***>; Mention ***@***.***>
Assunto: Re: [WouterJD/FortiusANT] TACX Bushido 1980 (Issue #431)


is it possible to have the executable?

Yes, I just uploaded it

**Comment by WouterJD** [comment] 2023-05-07 18:01
Good luck!

**Comment by gibabuscape** [comment] 2023-05-09 11:07
Hi Wouter. Not yet because my computer is in maintenace. As soon as possible I Will update you.  Tks Verry much

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Wouter Dubbeldam ***@***.***>
Enviado: Tuesday, May 9, 2023 6:31:02 AM
Para: WouterJD/FortiusANT ***@***.***>
Cc: Gilberto Faria ***@***.***>; Mention ***@***.***>
Assunto: Re: [WouterJD/FortiusANT] TACX Bushido 1980 (Issue #431)


Hi @gibabuscape<https://github.com/gibabuscape> how are things proceeding?

**Comment by bredy73** [comment] 2023-05-11 15:08
> I have a Bushido T1980 and I would like to know if there is anyone who has already installed FortiusAnt with Bkool? Are there any specific instructions for the T1980? @WouterJD

I think is not compatible, same as kinomap. At the moment it works with Rouvy and Zwift.

**Comment by WouterJD** [comment] 2023-05-11 20:13
Of course, I do not doubt that there are issues.
I know that many of the known CTP’s like Zwift, Trainer Road, Rouvy, Sufferfest, Golden Cheetah, Road Grand Tour, BigRingVR, TTS work with FortiusAnt. FortiusAnt uses a standard ANT-protocol, not tailored to any of thesae CTP's.

It might be an idea to use bluetooth and see what happens.

Could you please provide some more information on the pairing process and where things go wrong?

**Comment by WouterJD** [comment] 2023-05-11 21:10
With FortiusAnt and Bkool on the same Windows 10 PC, after activating FortiusAnt, Bkool finds the FortiusAnt ANT-devices right away. Note you need two ANT-dongles; for FortiusAnt and for Bkool.

@bredy73 and @gibabuscape I hope it helps, please let me know.

![image](https://github.com/WouterJD/FortiusANT/assets/47486941/fcb88895-fd82-4e86-a378-1470bf6f4814)

![image](https://github.com/WouterJD/FortiusANT/assets/47486941/947a8337-46ad-43d3-85e8-21fad43814ab)

**Comment by WouterJD** [comment] 2023-10-09 10:45
Since there is no communication here, I assume can be closed.
If not happy to reopen

**Comment by gibabuscape** [comment] 2023-10-09 12:14
Good morning

I apologize deeply for not having dedicated this topic, but I promise that as soon as I can test it again and if necessary, I would like to thank you for leaving the doors open to talk to you.

Best Regards
Gilberto Faria
De: Wouter Dubbeldam ***@***.***>
Enviada em: segunda-feira, 9 de outubro de 2023 07:46
Para: WouterJD/FortiusANT ***@***.***>
Cc: Gilberto Faria ***@***.***>; Mention ***@***.***>
Assunto: Re: [WouterJD/FortiusANT] TACX Bushido 1980 (Issue #431)


Since there is no communication here, I assume can be closed.
If not happy to reopen

**Comment by WouterJD** [comment] 2023-10-09 12:23
Hi @gibabuscape 

No problem at all; I'm waiting for your inputs and then we'll see whether I can help.

**Comment by bredy73** [comment] 2023-11-08 20:03
> With FortiusAnt and Bkool on the same Windows 10 PC, after activating FortiusAnt, Bkool finds the FortiusAnt ANT-devices right away. Note you need two ANT-dongles; for FortiusAnt and for Bkool.
> 
> @bredy73 and @gibabuscape I hope it helps, please let me know.
> 
> ![image](https://user-images.githubusercontent.com/47486941/237813748-fcb88895-fd82-4e86-a378-1470bf6f4814.png)
> 
> ![image](https://user-images.githubusercontent.com/47486941/237813399-947a8337-46ad-43d3-85e8-21fad43814ab.png)

I do not why, I use two dongle ant+, but my Bkool not recognized the bushido.

**Comment by WouterJD** [comment] 2023-11-08 20:09
Hi @bredy73 thanks for the update, this is as designed and looks good.

---
What do you mean with last phrase;
- did it not work in the past and does it work now 
- does it not work now?

**Comment by bredy73** [comment] 2023-11-09 19:55
For me it doesn't work. I don't know why.

**Comment by WouterJD** [comment] 2023-11-09 20:11
The screen looks good, note that FortiusAnt at the ANT+ side is "Tacx Neo" for the dimple reason that the non-Ant tacxes are not defined on the interface. So use tacx neo

**Comment by bredy73** [comment] 2023-11-11 08:06
I think the problem is the Ant+ because it doesn,t recognize even the cadence, speed and heart belt sensor.

**Comment by bredy73** [comment] 2023-11-12 08:34
My solution:
Connect only one Ant+ dongle, start Fortiusant.
Start Bkool and now connect the second Ant+ dongle. Now Bkool pairing Bushido and other sensor.

**Comment by WouterJD** [comment] 2023-11-28 18:40
Since there is no communication here, I assume can be closed.
If not happy to reopen

**Closed by WouterJD** 2023-11-28 18:40 UTC
Labels: question
